### ISSUE TITLE
Strict validation (column names/order)

### ISSUE THREAD

**Issue by parrellav** [travishorn/csval#10]
Is there a flag (or something that I need to specify in json schema) to get strict validation of the csv columns?  What I'm looking for is

1. The columns specified in the schema (and only those) are valid.  Changes to those column headers (order or type) cause failures.

Is there a way to do that in current functionality?  Would you like me to provide an example to better illustrate it?

**Comment by parrellav** [comment]
It seems like json schema allows for "additionalProperties" to be specified (boolean or a schema). Is this supported?

**Comment by parrellav** [comment]
based on my local testing, I think the problem lies on this line

https://github.com/travishorn/csval/blob/master/src/validate.js#L7

if that were changed to
`const schema = Enjoi.schema(rules).unknown(rules.additionalProperties);`

Then it would just work.  I have a PR ready to go but I'm checking with my company to see if they want this to go through their open source office or not.

**Comment by travishorn** [comment]
I haven't looked into `rules.additionalProperties`, but if the change doesn't break any tests, I don't have a problem merging it.

**Comment by travishorn** [comment]
Closed by #11
