### ISSUE TITLE
Something seems off here

### ISSUE THREAD

**Issue by parrellav** [travishorn/csval#13]
I just built a docker image with the latest version from this repo and it's not working as expected.  I had built one docker image locally (npm link) with my changes and it does respect additionalProperties.  The difference I'm seeing is that for some reason the latest from npm is flagging my test csv as having missing values when the regex for the column allows for empty values.  Also the column is not marked as a required field so I'm not sure of the difference.

I've verified inside the docker image that my changes are there but now it's not behaving as it should.  Is something possibly messed up with the release?

**Comment by parrellav** [comment]
I tried updating the dependencies since joi has been split out of hapi but that broke tests.  I'm also not a very seasoned node developer so i'm struggling with things

**Comment by travishorn** [comment]
One thing that may have been affecting this was that I didn't mark the latest version as "Latest Release" on GitHub. I've done that just now.

If the problem persists, I wonder if you can look at the diff between `src/validate.js` on your npm linked version vs the latest from npm.

**Comment by parrellav** [comment]
I just tried with the new version you published 1.1.1 and i'm still seeing the same issue.  I'm concerned its a library mismatch or something.

Not sure why regex would change so dramatically.

**Comment by parrellav** [comment]
This is the pattern I'm having a problem with
`"pattern": "([^|]*|)*[^|]*",`

It should match empty fields, but for some reason, this changed.

**Comment by travishorn** [comment]
You might be on the right track with dependency mismatch. I'm not sure how to resolve it but maybe focus on `package-lock.json` which dictates what exact versions of dependencies get installed.

**Comment by parrellav** [comment]
oddly enough (and this is odd) when I have a field defined in the json schema not required but has a regex, I'm able to get it to pass by setting minLength = 0 like this

`"ns3:divisions{{string:multi}}": {
			"type": "string",
			"pattern": "([^|]*|)*[^|]*",
			"minLength": 0,
                          "examples": [
				"Northeast",
				"West",
				"Central",
				"National"
			]
		}`

**Comment by parrellav** [comment]
Not sure how/why that would have changed with a version bump.  The only version difference I can see if a library called topo
