### ISSUE TITLE
is JSON Schema fully supported?

### ISSUE THREAD

**Issue by mariomuja** [travishorn/csval#2]
Your readme shows the following JSON Schema fragment 

```
{
  "type": "object",
  "properties": {
    "salary": {
      "type": "number"
    }
  }
}
```

However, this is not valid JSON Schema, right?
I mean, the $schema and definitions nodes are missing as shown in this example.

Does csval really support complete JSON Schema as the specification documents?

Thanks for your help,
Mario

```
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "definitions": {
        "Artist": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "founded": {
                    "type": "integer"
                },
                "members": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "required": [
                "founded",
                "members",
                "name"
            ],
            "title": "Artist"
        },
```
...

**Comment by travishorn** [comment]
The `$schema` and `definitions` are already handled by csval.

Think of each row in your CSV data as an **object** that's being validated. The rules are a single **definition**.

Your rules would be...

```
{
  "type": "object",
  "properties": {
      "name": {
          "type": "string"
      },
      "founded": {
          "type": "integer"
      },
      "members": {
          "type": "array",
          "items": {
              "type": "string"
          }
      }
  },
  "required": [
      "founded",
      "members",
      "name"
  ]
}
```

**Comment by mariomuja** [comment]
thanks a lot for your answer :-)

is it possible to have the information in the JSON Schema, which separator is used in the CSV (Semikolon, comma etc) and whether values are enclosed by single / double quotes ?

we must describe CSV formats delivered by different customers - some use semikolon, some use tab as separator, some have headers in the first row and some do not

we want to have this information in the JSON Schema to be able to validate all kinds of CSV files with the same validation routine

**Comment by travishorn** [comment]
csval uses [papaparse](https://www.papaparse.com/) to parse CSV files. By default, it will automatically detect delimiters and quoted fields. But it's not perfect.

Right now there's no way to explicitly define those things in csval. If you need it, you might consider forking the project and building in that feature. You might start with [this line](https://github.com/travishorn/csval/blob/master/src/parseCsv.js#L4), which contains the papaparse config object.
