### ISSUE TITLE
rules for co-existence of values

### ISSUE THREAD

**Issue by Nextdrive-NeilChen** [travishorn/csval#3]
Thank you for this great project!

I am trying to come up with a schema i.e.:

```
{
  "properties" : {
    "aaa": {
      "type": "string",
      "minLength": 0
    },
    "bbb": {
      "type": "string",
      "minLength": 0
    }
  }
}
```
such that bbb can not be "" when aaa is not ""; or bbb must be "" when aaa is ""; so the validate()  returns the error when either aaa or bbb is "", returns true when not both "" or both having values.

I am very new to programming; and I have tried to look through the JSON Schema documentations and your examples but I have not found a right direction. Would you please give me some tips? Thank you so much.

**Comment by Nextdrive-NeilChen** [comment]
[edited] I made a mistake (both "required" and "dependencies" should be on the root level) thus I edited the JSON below, **thank you Travis for pointing that out**. You are right about that enjoi does mention that not all json-schema definitions are supported. I guess I need to study enjoi further more.

I learned that "Dependencies" is the way to go. But I think(maybe?) it's not yet implemented in the lib this project refers. If anyone is interested, this schema will probably work:
```
{
  "properties" : {
    "aaa": {
      "type": "string",
      "minLength": 0
    },
    "bbb": {
      "type": "string",
      "minLength": 0
    }
  },
  "required": ["aaa", "bbb"],
  "dependencies": {
    "aaa": ["bbb"],
    "bbb": ["aaa"] 
  }  
}
```

**Comment by travishorn** [comment]
In your example, `required` and `dependencies` are children of `properties`, when they should really be siblings (on the root level alongside `properties`).

I haven't used `dependencies` before. But if it doesn't work here, it's most likely because [enjoi](https://github.com/tlivings/enjoi) doesn't support it. The developer does mention that enjoi does not support all of json-schema.
