### ISSUE TITLE
Delimiter support and schema issue

### ISSUE THREAD

**Issue by parrellav** [travishorn/csval#6]
Hi Travis,

I've started playing around with this csval and so far I like it but I've got a few questions

1. Are delimiters other than comma supported?
2. I'm running into an issue specifying a second field for validation.  I believe I've got a valid CSV (csval told me that when I tried it without a schema) but when I add a second field for validation, it fails for all rows.  Can I get some help?

Thanks.

**Comment by travishorn** [comment]
Hello,

### 1
The delimeter is automatically detected. However, you could modify csval to set a specific delimiter by changing [line 4 of src/parseCsv.js](https://github.com/travishorn/csval/blob/24ec987000b3e687b745c339c2cc6510cee6d9a8/src/parseCsv.js#L4).

```
const parsed = parse(data, { header: true, skipEmptyLines: true });
```

becomes

```
const parsed = parse(data, { header: true, skipEmptyLines: true, delimiter: "x" });
```

### 2
You can see an example of validation for multiple fields on [sample-rules/employees.json](https://github.com/travishorn/csval/blob/master/sample-rules/employees.json)

```
{
  "properties": {
    "Employee ID Number": {
      "type": "string",
      "pattern": "^100\\d{6}$"
    },
    "Last Name": {
      "type": "string",
      "minLength": 1,
      "maxLength": 30
    },
    // ... snipped code ...
  },
}
```

**Comment by parrellav** [comment]
Thanks @travishorn 

It turns out the CSV I was using had a leading "|" and I was able to work my way through the multiple properties issue I saw.

Thanks for getting back to me so promptly and really excellent job on this software 👍
